#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)
#Let’s also add other subdomains to make our life easier, and write a Bash script that will display information about subdomains.

dns_config () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_config "$1" "www"
  dns_config "$1" "www"
  dns_config "$1" "www"
  dns_config "$1" "www"
elif [ "$#" == 2 ]
then
  dns_config "$1" "$2"
fi
